TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

LIBRARY_IOC += timeStampFifo

LIB_SRCS += timeStampFifo.cpp camera_ts.cpp

DBD += timeStampFifo.dbd

DB  += timeStampFifo.template

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

